---
on: push

jobs:
  build:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: github/super-linter@v4.10.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
